### PR TITLE
Detect, read and parse CSVs and save to Json

### PR DESCRIPTION
**Pull request by chriscamplin**
> Which issue, if any, is this issue related to?

The project directory is scanned for CSV/TSVs. If found these are parsed to a flat data structure, using headings as column names.
A config file is used to define which targetDirectory to start recursively searching for CSVs. Any directories to exclude, any additional fileTypes and which column separator the parser should use, can also be defined.
Currently data is saved as a Json file in a src/data
Tests use Jest and mocks replace the fs API during. More testing should be implemented.

### CODE REVIEW

**Review by tomgp — APPROVED** [review]
👍🏼 This is good for a first draft.
The only necessary fix is the hardcoded JSON filename

**Review by tomgp — APPROVED** [review]

**Comment by tomgp** [comment]
Having given it some thought over the weekend I don't think mocking fs for tests makes much sense here. The integration with the filesystem is the thing we _want_ to test. I think it'll be better to make a test directory and write tests against that.

**Comment by chriscamplin** [comment]
@tomgp I was actually thinking about rewriting the tests over the weekend too, I'll put some more time into this.

**Comment by tomgp** [comment]
> @tomgp I was actually thinking about rewriting the tests over the weekend too, I'll put some more time into this.

Let's merge this. And sort test out after a chat.

**Review by marcelkornblum — APPROVED** [review]
could we start

**Comment by chriscamplin** [comment]
@marcelkornblum @tomgp If you are waiting for me I don't have permission to merge this:
Screenshot 2021-02-08 at 15 20 33

**Comment by marcelkornblum** [comment]
Not sure my above comment was entirely intentional! Also will figure out permissions, you're not meant to be forbidden sorry Chris!

**Pull request merged**
